# Generated by Django 5.2.17 on 2026-09-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('challenge_type', models.CharField(choices=[('web', 'Web Exploitation'), ('crypto', 'Cryptography'), ('forensics', 'Forensics'), ('binary', 'Binary Exploit/Reverse Engineering')], max_length=20)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('solved', 'Solved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='solver.challenge')),
            ],
        ),
    ]
